### ISSUE TITLE
[section_request] Ansible Playbook Bundles

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/ansible-for-kubernetes#1]
Would like to see some discussion around ansible playbook bundles / ansible service brokers and the service catalog.

@leifmadsen willing to collaborate. Already has working examples, documentation, etc.

**Comment by geerlingguy** [comment]
I haven't actually heard of APB/ASBs, as it sounds like it's something that's more specific to OpenShift (is that a correct understanding?).

Would these be the most relevant resources?

  - https://github.com/openshift/ansible-service-broker
  - https://docs.openshift.com/container-platform/4.2/applications/service_brokers/installing-ansible-service-broker.html

**Comment by leifmadsen** [comment]
Yes, but they are now deprecated in favour of Ansible Operators via the operator-sdk. This issue is no longer relevant.

The request is still valid to show some sort of automation around OperatorHub (OperatorHub.io would be a valid place) because this can be done via vanilla Kubernetes, but APB/ASB can be ignored.

**Comment by geerlingguy** [comment]
Sounds good, then! Closing this issue in favor of #2, and I expect to also be doing some work around pulling operators from various places (notably, OperatorHub.io) to run some real-world applications, in later chapters.
