### ISSUE TITLE
s/you/your in Chapter 2

### ISSUE THREAD

**Issue by aharden** [geerlingguy/ansible-for-kubernetes#10]
Chapter 2, Managing Kubernetes with Ansible/Managing Minikube:
“(at least as of this writing—you could write you own!)” should be “(at least as of this writing—you could write your own!)”

**Comment by geerlingguy** [comment]
Thanks! I have fixed this in the book's text, and it will be included in the next set of changes I'll push up to LeanPub soon (hopefully before the new year).

**Comment by aharden** [comment]
Cool.  It's been a great read so far.
