### ISSUE TITLE
Leanpub link is broken

### ISSUE THREAD

**Issue by stephen-elves** [geerlingguy/ansible-for-kubernetes#114]
https://leanpub.com/ansible-for-kubernetes just results in an empty leanpub page.

**Comment by rclilly** [comment]
@stephen-elves It works for me.

**Comment by geerlingguy** [comment]
@stephen-elves - Yeah, not sure what the issue is :(

**Comment by stephen-elves** [comment]
Working now for me too, suspect it’s was down temporarily.
