### ISSUE TITLE
Ansible 101 questions 

### ISSUE THREAD

**Issue by kant777** [geerlingguy/ansible-for-kubernetes#121]
I tried reading serveral docs and running some examples using ansible but I cannot find answers to below questions. any suggestions will be great

1. I see that ansible roles are mainly used to deploy applications but what about provisioning infra? like say launch a VM or launch a AWS EKS Cluster etc. How does this fit into the directory structure as stated [here](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout)

2. when not to use a role?

3. Why does inventory takes only hostnames? why cant it be list of items like list of cluster names? For example I want to launch multiple AWS EKS clusters and I want to run same set of tasks for each cluster which means each set should run in parallel. For now, I am only able to do that using `vars.yml` to define cluster names and `with_items` in my taks to loop through

**Comment by geerlingguy** [comment]
Some of those questions are answered in my other book [Ansible for DevOps](https://www.ansiblefordevops.com). Ansible for Kubernetes assumes you already have some familiarity with Ansible, since Kubernetes on top of everything else is a lot more complexity!
