### ISSUE TITLE
Add CI coverage for cluster-aws-eks example

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-kubernetes#15]
As the title says, add CI coverage (as much as possible) to the [cluster-aws-eks](https://github.com/geerlingguy/ansible-for-kubernetes/tree/master/cluster-aws-eks) example.

Since it relies on CloudFormation templates, maybe the main thing to do would be to validate them, and run ansible-lint on the playbook, and maybe something like `--syntax-check`. Otherwise I'd have to wire up a live AWS account to Travis CI, and I'm loathe to do that, especially when clusters cost $0.20/hour!

**Comment by nicolas-g** [comment]
just an idea, you could also use **Minikube** or **Kind** .

**Comment by geerlingguy** [comment]
@nicolas-g - For these particular examples, the point of the test is to verify the CloudFormation templates are correct and create a functional EKS cluster, which unfortunately can't be tested through Minikube, KinD, or any of the other CI-friendly Kubernetes cluster solutions.

I might also add a test to make sure the Wordpress manifests run independently, just for a sanity check, but the main thing I need to test is hard to test via CI since it would require a functional AWS account (and would take at least 20-30 minutes per run, since EKS clusters are notoriously sluggish to start—and to stop!).

**Comment by geerlingguy** [comment]
Initial tests are added above. Note that I need to re-test all the templates, as `cfn-lint` found a few extra refs and suggested some type changes that may or may not have affected the templates' ability to run perfectly :)

**Comment by geerlingguy** [comment]
Full tests for this example take approximately 3 minutes. Looking good now! Just had to drop the `aws cloudformation validate-template` test because it requires valid AWS credentials, and I'm loathe to add them to my Travis CI job configuration, even for a very limited IAM user.

**Comment by geerlingguy** [comment]
Re-tested everything on live AWS account, and it works great!
