### ISSUE TITLE
Typo 'containter' in Ch.1

### ISSUE THREAD

**Issue by qmacro** [geerlingguy/ansible-for-kubernetes#18]
In section "Running Hello Go in Docker", there's "containter" in the Information note:

_This book will mostly use Docker in its examples due to its ongoing popularity, but know there are other containter runtimes worth investigating_

**Comment by geerlingguy** [comment]
Ha, don't let your servers get tainted with containters! Thanks for posting this, I'll have it fixed in the next version of the book.
