### ISSUE TITLE
Typo "it's" in Ch.2

### ISSUE THREAD

**Issue by qmacro** [geerlingguy/ansible-for-kubernetes#19]
In the section "Ansible 101" there's "_known for it's simplicity_" where it should be "its". 

(BTW hope these super minor things are OK with you - I am *loving* the book and how much I'm learning).

**Comment by geerlingguy** [comment]
Not annoying at all, rather extremely helpful! I try to catch these things in my own edits but especially for things like `it's` and `its` usage, I have some weird mental block sometimes to getting it correct :)

**Comment by geerlingguy** [comment]
This is fixed and will be in the next version of the book. Thanks again!
