### ISSUE TITLE
[section_request] Operators

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/ansible-for-kubernetes#2]
Discuss operators, and the Ansible Operator as part of the Operator SDK framework.

* https://github.com/operator-framework/operator-sdk
* https://github.com/operator-framework/operator-sdk/labels/ansible-operator

@leifmadsen willing to help.

**Comment by geerlingguy** [comment]
To provide an update here (oops, it's been over a year!), I have been working on a variety of operators (so far none super in-depth, but that's happening now), and will likely use one or two as examples through one or two chapters:

  - https://github.com/geerlingguy/mcrouter-operator
  - https://github.com/geerlingguy/drupal-operator
  - https://github.com/geerlingguy/mariadb-operator
  - https://github.com/geerlingguy/tower-operator

**Comment by geerlingguy** [comment]
Closing this in favor of #33, which is the same thing but with a couple more specific examples.
