### ISSUE TITLE
Reference to unused "connection" keyword in Ch.2

### ISSUE THREAD

**Issue by qmacro** [geerlingguy/ansible-for-kubernetes#20]
In the first warning note in the "Hello, Ansible!" section you refer to a `connection` keyword that hasn't been referenced so far.

**Comment by geerlingguy** [comment]
Thanks; that was from an initial version of the playbook which defined the `connection: local` inside the playbook instead of the inventory, but as you say it doesn't make sense there with the current version of the playbook!

I'll have this fixed in the next book release.
