### ISSUE TITLE
Reference to `minikube_status` as command 

### ISSUE THREAD

**Issue by qmacro** [geerlingguy/ansible-for-kubernetes#21]
In Ch.2 section "Managing Minikube", there's:

"_If there is no output from the `minikube_status` command_"

I think that this perhaps should be `minikube status`, without the underscore, as `minikube_status` is the register rather than the command.

**Comment by geerlingguy** [comment]
Ah, you are correct. I'll have this fixed in the next version of the book! Thanks.
