### ISSUE TITLE
Typo missing "e" in Chapter 2-Managing Kubernetes with Ansible-Managing Minikube

### ISSUE THREAD

**Issue by BernardoEstevao** [geerlingguy/ansible-for-kubernetes#38]
Chapter 2 > Managing Kubernetes with Ansible > Managing Minikube
In the third paragraph there is a typo in the first word: "**Crate** a new directory (...)". Should be **Create**

Great book so far, good job

**Comment by geerlingguy** [comment]
Ha, sorry about that! David R also emailed me about this separately. I have it fixed and will be pushing out an update with this fix very soon!
