### ISSUE TITLE
Mirantis misspelled in Chapter 1

### ISSUE THREAD

**Issue by dwaiting** [geerlingguy/ansible-for-kubernetes#39]
In this paragraph

> Docker vs. Podman: Docker users wonder about the future of Docker CE and moby, the engine that runs Docker containers. Events like the sale of ‘Docker Enterprise’ to Marantis in 2019 did nothing to quell fears about Docker’s future, and many developers who rely on containers for their application deployment have been seeking alternative container builders and runtimes.

The correct spelling is _Mirantis_

**Comment by geerlingguy** [comment]
Oops, good catch! I'll have this fixed in the next batch of updates, coming soon.
