### ISSUE TITLE
Port is variable in Chapter 4 - Building K8s clusters with Ansible

### ISSUE THREAD

**Issue by benheu** [geerlingguy/ansible-for-kubernetes#42]
Not sure where is the port defined for the hello-kubernetes page service but in my case it's a different one than the one in the book (port 30297 instead of 30606):

> This time it works! With the two networking adjustments, we’ve fixed our Kuber-
> netes cluster. If you open a browser window, you should even be able to see the
> hello-kubernetes page by accessing the NodePort on any of the three servers, e.g.
> http://192.168.7.3:30606 .

Maybe you can add a final task at the end of test-deployment.yml to avoid confusion :
```
- name: Print out kubernetes-hello page url
   debug:
     msg: "http://{{ ansible_host }}:{{ port }}/"
```

**Comment by geerlingguy** [comment]
Good point! I'll add that to the example, it's definitely not clear with the way the book is written that the port is variable and there's about a 99% likelihood it won't be exactly `30606` :D
