### ISSUE TITLE
Warn users that the `k8s_info` module was `k8s_facts` before Ansible 2.9

### ISSUE THREAD

**Issue by nejch** [geerlingguy/ansible-for-kubernetes#43]
Thanks a lot for the great read! I'm not sure if this should be in the scope of the book, since this might be an issue with other modules as well, but just thought I'd mention it. Chapter 4 uses the `k8s_info` module to gather service facts, which was called `k8s_facts` before Ansible 2.9.

I'm executing the playbooks from a repo with GitLab CI rather than locally, using the `ansible/ansible-runner:latest` image from https://hub.docker.com/r/ansible/ansible-runner. I'm not sure this is the greatest idea (I thought I'd eventually use the added runner capabilities), but anyway - the latest runner image is currently still at Ansible 2.8 - so the deployment test in Chapter 4 was failing with `ERROR! no action detected in task.`

**Comment by bmillemathias-1a** [comment]
> Chapter 4 uses the `k8s_info` module to gather service facts, which was called `k8s_facts` before Ansible 2.9.

If I remember correctly the text states as the beginning the code was made against ansible 2.9.x so that implicitly tells that other version are likely not to work out-the-box.

**Comment by geerlingguy** [comment]
@bmillemathias-1a - True, however I still have some references to changes which occurred in Ansible 1.9, 2.0, 2.4, etc. in my Ansible for DevOps book... so it can't hurt to be clear in areas where people get tripped up like @nejch did :)

I'll definitely add a note somewhere around the first time I start using the module.

**Comment by geerlingguy** [comment]
I have added an info box after the first use of `k8s_info` in chapter 4 with a note about using `k8s_facts` if using Ansible 2.8 or earlier. Thanks again for mentioning this!
