### ISSUE TITLE
[erratum] Possible Typo. Crate -> Create.

### ISSUE THREAD

**Issue by lnyaki** [geerlingguy/ansible-for-kubernetes#44]
**Book version** 0.3.
**Chapter 2**: Automation brings DevOps bliss
**Section**: Managing Minikube
**Page**: number 27.
Third paragraph.

_Current sentence, with the assumed error_:
"**Crate** a new directory hello-go-automation (next to the hello-go directory) with the same inventory file as used in the previous example, and add a main.yml playbook."

_Proposed correction_:
"**Create** a new directory hello-go-automation (next to the hello-go directory) with the same inventory file as used in the previous example, and add a main.yml playbook."

**Comment by geerlingguy** [comment]
Thanks for the report! I just fixed this in the manuscript yesterday; see https://github.com/geerlingguy/ansible-for-kubernetes/issues/38

It will be in the next version of the book, released 'soon' :)
