### ISSUE TITLE
Support: cleanest way to assign more memory to kube1

### ISSUE THREAD

**Issue by torenware** [geerlingguy/ansible-for-kubernetes#47]
In Chapter 4 of A4K8s, you describe the [Vagrantfile](https://github.com/geerlingguy/ansible-for-kubernetes/blob/master/cluster-local-vms/Vagrantfile) used to create a local Virtualbox-based cluster.

I'm using the configuration to study a number of topics, including Istio. This will require more memory on kube1 than the default 2Gi.  As currently written, all 3 hosts get their memory in the first config block:

```ruby
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
    v.customize ['modifyvm', :id, '--audio', 'none']
  end
```

I'd like to add a symbol (say, `:memory`) to the boxes array for memory, potentially just for kube1.

What's the cleanest way to change the script so that I can have 4Gi memory for kube1, but the default 2Gi for kube2 and kube3?

**Comment by geerlingguy** [comment]
You would probably need to do something like this blog post, defining the provider information for each of the hosts: https://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/

There are other cleaner ways to do it using loops, maybe, but it starts getting a little more messy.
