### ISSUE TITLE
Hash mismatch when downloading docker

### ISSUE THREAD

**Issue by B45man** [geerlingguy/ansible-for-kubernetes#48]
Hi, I'm in chapter 4 of this book. I have created 3 VM's using Vagrant. I have downloaded the source code from this repo for chapter 4. When running `ansible-playbook -i inventory main.yml` I see the below error: 

![image](https://user-images.githubusercontent.com/6691945/80709295-5a97c700-8aed-11ea-9bd1-eb0b54e13d2b.png)

I couldn't copy-paste from my terminal window, sorry. This is the only part the playbook seems to fail on. The other steps are successful.

**Comment by geerlingguy** [comment]
@bmillemathias-1a - Can you try running `apt-get update` inside the VM and see if that fixes it up?

**Comment by geerlingguy** [comment]
This may be related to https://github.com/geerlingguy/ansible-for-kubernetes/issues/57 — I am going to re-test the playbook on my laptop now and see if I can reproduce the error.

**Comment by geerlingguy** [comment]
I just re-ran the build fresh on my laptop and didn't seem to run into an error. I'm guessing it was a transient issue with maybe one of the apt caches or something in the image. I would recommend doing a full `vagrant destroy` then bringing it up again, and make sure you're on the latest versions of Vagrant, all the roles (`ansible-galaxy install --force -r requirements.yml`), etc.
