### ISSUE TITLE
Link for 'Installing Minikube' is bad

### ISSUE THREAD

**Issue by 0xSheepdog** [geerlingguy/ansible-for-kubernetes#50]
Chapter 1. Section "Installing Minikube" - the link points to https://minikube.sigs.k8s.io/docs/start/linux/ which does not work for me.
removing linux/ from the URI takes me to the minikube start page where you can select linux (default), macOS, or Windows.

**Comment by geerlingguy** [comment]
D'oh! That link worked just a couple months ago. I see the Minikube SIG is not as interested as I am in preserving URLs and redirects forever 😁

I'll get this fixed in the next release of the book. Thanks for finding the issue!
