### ISSUE TITLE
[erratum] grammatical - simultaneous use of 'a' and 'the' 

### ISSUE THREAD

**Issue by shuklalok** [geerlingguy/ansible-for-kubernetes#51]
Book Version: 0.3
PDF Version, Page 66.
Chapter 3 - Ansible Manages Containers
Heading - Apache Solr container build summary.
First Line - _"Sometimes building container images with a Dockerfile is **a the** best choice._
Suggested changes: Any of the following:

1. _"Sometimes building container images with a Dockerfile is **a/the** best choice._
2. _"Sometimes building container images with a Dockerfile is **a good** choice._
3. _"Sometimes building container images with a Dockerfile is **the best** choice._

**Comment by geerlingguy** [comment]
Yikes! I'll have to fix that in the next version of the book. Thanks for catching this.

**Comment by geerlingguy** [comment]
I have this fixed in the manuscript and it will be in the next version of the book. Thanks for spotting this!
