### ISSUE TITLE
Update EKS version to 1.17

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-kubernetes#59]
See: https://github.com/aws/containers-roadmap/issues/697

**Comment by geerlingguy** [comment]
(And here's the issue for 1.18: https://github.com/aws/containers-roadmap/issues/809)

**Comment by abdennour** [comment]
Also this link might be useful https://github.com/terraform-aws-modules/terraform-aws-eks/pull/949 
I know  that here it is about ansible roles... but let's see which one will be the first available: TF module or Ansible role.
