### ISSUE TITLE
Virtualenv for ansible and/or ansible+rundeck container in cluster.

### ISSUE THREAD

**Issue by timoc** [geerlingguy/ansible-for-kubernetes#60]
One of the annoying issues we have had with ansible has been that you need to upgrade your scripts whern there are changes in versions of python or anisble in the host OS. 

We have tried twio solutions:
1: Ansible has been notoriously sensitive to changes in the python environment, especially on the system where the ansible script is invoked. Python virtualenv allows you to manage the python runtime environment you develop and run your scripts in.

2, A barebones "managment server" in the k8s cluster, specifically setup with the correct python environment, ansible version etc. This in conjuntion with a tool like rundeck, allows a kind of self service approach to cluster maintainance. 

or a better option?

**Comment by geerlingguy** [comment]
@timoc - Often the best solution is to run Ansible via Tower or AWX (https://github.com/ansible/awx), as that provides a stable environment inside which Ansible playbooks can run.

Other than that, I often run Ansible in a Jenkins environment, or in a container that I build new for every new Ansible release. That approach seems to also be the approach Ansible Tower is moving towards with their new 'Execution Environments' feature; see [Ansible Builder](https://github.com/ansible/ansible-builder).
