### ISSUE TITLE
need ignore-certs to download roles with ansible-galaxy

### ISSUE THREAD

**Issue by nleeuskadi** [geerlingguy/ansible-for-kubernetes#62]
Hi,

Following your book "ansible for kubernetes" chapter 4 section "Building a server with roles", I am facing an issue while executing  the command `ansible-galaxy install -r requirements.yml` 

> [WARNING]: - geerlingguy.security was NOT installed successfully: Unknown error when attempting to
call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

I fixed it adding the following section in the ansible.cfg:
>[galaxy]
ignore_certs = yes

in case it could help

best regards

**Comment by geerlingguy** [comment]
Thanks for posting this—usually when this happens it either has to do with Galaxy having out of date certificates (less likely, but it could happen), or your system either not supporting SNI (if you're on CentOS or older OSes that could be the case) or not having the latest ca-certificates installed on the system (I know Galaxy uses a little different certificate than some other sites that I normally interact with).

If you still get this issue and you can confirm that your system is all up to date, I'd consider filing an issue in Ansible's Galaxy github repository with steps to reproduce and what versions of OS, certificates, etc. you have.
