### ISSUE TITLE
Ch 4, pg 72 typo

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-kubernetes#64]
Should be "list"

![image](https://user-images.githubusercontent.com/19269683/90559545-55758b00-e163-11ea-86dd-cdfcb26543f5.png)

**Comment by geerlingguy** [comment]
This typo find is lit 🔥

Thanks for submitting the issue; I'll get the text updated in the next revision of the book!

**Comment by geerlingguy** [comment]
This is fixed in the book's manuscript and will be in the next version of the book. Thanks so much!
