### ISSUE TITLE
Chapter 5 pg 113 typo

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-kubernetes#65]
I believe main/vars.yml is switched given the rest of the paragraph

![image](https://user-images.githubusercontent.com/19269683/90715702-b0e16f00-e270-11ea-96b7-9bfe28970fe7.png)

**Comment by geerlingguy** [comment]
Ha, yes, you are correct! I'll get this fixed in the next version of the book.

**Comment by geerlingguy** [comment]
This is fixed in the book's manuscript and will be in the next version of the book. Thanks so much!
