### ISSUE TITLE
Error with 'aws-iam-authenticator' running off the page in chapter 5

### ISSUE THREAD

**Issue by typ-ex** [geerlingguy/ansible-for-kubernetes#66]
![image](https://user-images.githubusercontent.com/19269683/90935531-06c92a80-e3c9-11ea-96c0-3d65f5c49bf6.png)
Special tool runs right off the page

**Comment by geerlingguy** [comment]
D'oh! This is an issue I sometimes run into with fixed-width text an LeanPub's output.

Can you tell me what type of download you're using to read the book? (Epub, Mobi, or PDF)

**Comment by typ-ex** [comment]
PDF

**Comment by geerlingguy** [comment]
I'll check into the output and try to get this to lay out a little better.

**Comment by geerlingguy** [comment]
This should be fixed in the next version of the book, coming very soon!
