### ISSUE TITLE
requirements.yml style question

### ISSUE THREAD

**Issue by whitesscott** [geerlingguy/ansible-for-kubernetes#7]
requirements.yml needs updated to your new galaxy structure to include k8s
from   - name: geerlingguy.kubernetes
to       - name: geerlingguy.k8s.kubernetes

**Comment by geerlingguy** [comment]
The current style should work fine, I've tested with Ansible 2.8 and 2.9...

What error do you get if you use the current style?

**Comment by geerlingguy** [comment]
Ah, you might be referring to the fact there's a 'kubernetes' role inside the k8s collection—there's also a standalone role available on Galaxy (indeed, the one I update more frequently), and that's what's being used in the examples in the book.

For _now_, I'm sticking with roles in my examples. At some point in the future (maybe Ansible 2.10, 2.11, or beyond), I'll likely switch the examples to start using collections... but the transition plan is a little messy right now (upstream in Ansible), so I'm going to close this issue as 'works as designed' for now.
