### ISSUE TITLE
Chapter 4 - cgroup issue "missing optional cgroups: hugetlb"

### ISSUE THREAD

**Issue by eternal44** [geerlingguy/ansible-for-kubernetes#80]
Hi Jeff,

I wanted to start by saying thanks for writing this book - it's been a joy learing about infrastructre with you!

I was running the playbok for chapter 4 and was stuck trying to solve an error and was hoping to get some help; could you point me in the right direction?

I ran the following commands at the root of the `cluster-local-vms` project directory ([click for github link](https://github.com/geerlingguy/ansible-for-kubernetes/tree/master/cluster-local-vms)):
```
  ansible-galaxy install -r requirements.yml
  asible-playbook -i inventory main.yml
```

and got this error:
```
TASK [geerlingguy.kubernetes : Join node to Kubernetes master] ****************************************************************************************************************************************************

{
  "changed": true,
  "cmd": "kubeadm join 10.0.2.15:6443 --token qpmkrn.igfx2l1qot6s6iy1     --discovery-token-ca-cert-hash sha256:f18819f8d7e8745367f76ad09519e038c3315753c597ebc37df795b49aa36345  \n",
  "delta": "0:05:00.321336",
  "end": "2020-12-21 05:34:41.261163",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2020-12-21 05:29:40.939827",
  "stderr": "\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\n\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.1. Latest validated version: 19.03\n\t[WARNING SystemVerification]: missing optional cgroups: hugetlb\nerror execution phase preflight: couldn't validate the identity of the API Server: Get \"https://10.0.2.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s\": dial tcp 10.0.2.15:6443: connect: connection refused\nTo see the stack trace of this error execute with --v=5 or higher",
  "stderr_lines": [
    "\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at htt ps://kubernetes.io/docs/setup/cri/",
    "\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.1. Latest validated version: 19.03",
    "\t[WARNING SystemVerification]: missing optional cgroups: hugetlb",
    "error execution phase preflight: couldn't validate the identity of the API Server: Get \"https://10.0.2.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeo ut=10s\": dial tcp 10.0.2.15:6443: connect: connection refused",
    "To see the stack trace of this error e xecute with --v=5 or higher"
  ],
  "stdout": "[preflight] Running pre-flight checks",
  "stdout_lines": [
    "[pre flight] Running pre-flight checks"
  ]
}


PLAY RECAP ********************************************************************************************************************************************************************************************************
kube1                      : ok=52   changed=4    unreachable=0    failed=0    skipped=22   rescued=0    ignored=0
kube2                      : ok=43   changed=2    unreachable=0    failed=1    skipped=20   rescued=0    ignored=0
kube3                      : ok=43   changed=2    unreachable=0    failed=1    skipped=20   rescued=0    ignored=0
```

The link from the error message has instructions for hwo to configure `k8s` to use `systemd` but it looked like a deadend since we're using `ansible`. I then noticed you're using [`cgroup` to configure ansible roles](https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/molecule/default/molecule.yml#L11) but figured maybe the issue was with my local environment because that code change was from ~2 years ago and I don't see any related issues in the repo issues.

Any suggestions on what to try next?

**Comment by geerlingguy** [comment]
Hmm... The `missing optional cgroups: hugetlb` error doesn't seem fatal (it's just a warning—as is the Docker error above it...) and I think it seems more like it could be a networking issue... e.g. `10.0.2.15` might be an internal private IP and the node might not be seeing the master server.

**Comment by eternal44** [comment]
Thank you, haha in a strange twist of sentiments I understood very little of your response but I appreciate them anyway because:
```
I now know (or atleast more familiar with) what I don't know
```
and I have a general direction I can continue on.

I'll close the issue to keep your queue clean but if you see the benefit of keeping it open please feel free to do so.

**Comment by ctrahey** [comment]
Sharing for posterity / future googlers: 

Enabling the hugetlb cgroups with the technique at the top of [this page ](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/hugetlb.html)worked to remove this warning for me:
```
mount -t cgroup -o hugetlb none /sys/fs/cgroup
```

(this after recompiling the kernel to include this feature, as my kernel did not have it by default - RPi Ubuntu)
