### ISSUE TITLE
Playbooks in chapter 3 are missing 'ansible_python_interpreter' variable.

### ISSUE THREAD

**Issue by gimballock** [geerlingguy/ansible-for-kubernetes#91]
https://github.com/geerlingguy/ansible-for-kubernetes/blob/555e16d04326ce54d998f7ec78e753799074f47e/ansible-containers/main.yml#L5

I needed to add this variable (copied from chapter 2's examples) to main.yml and registry.yml in order to avoid the following error:

> fatal: [127.0.0.1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on MacBook-Pro.local's Python /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named requests.exceptions"}

**Comment by typ-ex** [comment]
I didn't need it when I ran the playbooks.  Do you have python2 and python3 installed on your macbook?

**Comment by gimballock** [comment]
Yes I have both installed. Mac comes with python 2.7 pre installed as 'python' and I believe the os needs it to be there.  I have also python3 using homebrew.

```
~ ls -alF $(which python)
lrwxr-xr-x  1 root  wheel  75 Jan  1  2020 /usr/bin/python@ -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
```

```
ls -alF $(which python3)
lrwxr-xr-x  1 eprice  admin  38 Feb 22 16:30 /usr/local/bin/python3@ -> ../Cellar/python@3.9/3.9.2/bin/python3
```

I have also tried including this in my shell rc to map v3 tools to the original path:
```
alias python=/usr/local/bin/python3
alias pip=/usr/local/bin/pip3
```

**Comment by gimballock** [comment]
I found another local python installed at /usr/bin/python3
```
$ /usr/bin/python3 --version
Python 3.8.2
```
but I don't think anything is referencing it.

**Comment by typ-ex** [comment]
If you don't want to do that for future ansible playbooks, you can look up the documentation on ansible.cfg and set the default interpreter to the version of python you want.

**Comment by gimballock** [comment]
Ahh I see: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#interpreter-python

Also everything in this file is overridable with env vars.
